version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app-1
      - app-2
    restart: always

  app-1:
    build:
      context: ./app-1
      dockerfile: Dockerfile
    expose:
      - 3000
    restart: always

  app-2:
    build:
      context: ./app-2
      dockerfile: Dockerfile
    expose:
      - 3000
    restart: always